#!/bin/bash
# WARNING: RUN THIS SCRIPT FROM THE start DIRECTORY
CMAKE=CMakeLists.txt
SRC=src

rm -rf $SRC/*
mkdir -p $SRC
unzip -d $SRC start.atzip > /dev/null 2>&1

find $SRC -type f -exec dos2unix {} \; 2> /dev/null

# these directories contain source code for other compilers and will throw errors when given to gcc
rm -fr $SRC/samc21/armcc
# we don't need their main
rm -f $SRC/main.c

echo "#WARNING: this CMakeLists.txt file is automatically generated by the \"update.sh\" script!
cmake_minimum_required(VERSION 3.16)

add_library(BOOTLOADER_START OBJECT)
target_compile_options(BOOTLOADER_START PRIVATE -Wno-unused-parameter -Wno-conversion -Wno-sign-conversion -Wno-expansion-to-defined -Wno-implicit-fallthrough -Wno-overflow -Wno-undef)

target_include_directories(BOOTLOADER_START PUBLIC" > $CMAKE

find $SRC -type d | grep -iv example | while read line ; do
   echo -e "\t\${CMAKE_CURRENT_LIST_DIR}/$line" >> $CMAKE
done

echo "        )

target_sources(BOOTLOADER_START PRIVATE" >> $CMAKE

find $SRC -type f | grep -iv example | while read line ; do
   echo -e "\t\${CMAKE_CURRENT_LIST_DIR}/$line" >> $CMAKE
done

echo "        )" >> $CMAKE

exit 0
