#!/bin/bash
# usage: ./generate.sh /path/to/input.atzip /path/to/output/dir

set -eu

INPUT_FILE=$1
OUTPUT_DIR=$2

CMAKE=CMakeLists.txt

rm -rf $OUTPUT_DIR/*
mkdir -p $OUTPUT_DIR
unzip -d $OUTPUT_DIR $INPUT_FILE > /dev/null 2>&1

find $OUTPUT_DIR -type f -exec dos2unix {} \; 2> /dev/null

# these directories contain source code for other compilers and will throw errors when given to gcc
rm -fr $OUTPUT_DIR/samc21/armcc
# we don't need their main
rm -f $OUTPUT_DIR/main.c

echo "#WARNING: this CMakeLists.txt file is automatically generated by the \"generate.sh\" script!
cmake_minimum_required(VERSION 3.16)

add_library(START OBJECT)
target_compile_options(START PRIVATE -Wno-unused-parameter -Wno-conversion -Wno-sign-conversion -Wno-expansion-to-defined -Wno-implicit-fallthrough -Wno-overflow -Wno-undef)

target_include_directories(START PUBLIC" > $CMAKE

find $OUTPUT_DIR -type d | grep -iv example | while read line ; do
   echo -e "\t\${CMAKE_CURRENT_LIST_DIR}/$line" >> $CMAKE
done

echo "        )

target_sources(START PRIVATE" >> $CMAKE

find $OUTPUT_DIR -type f -name "*.c" | grep -iv example | while read line ; do
   echo -e "\t\${CMAKE_CURRENT_LIST_DIR}/$line" >> $CMAKE
done

echo "        )" >> $CMAKE

exit 0
